version: "3.8"

services:
  openldap:
    image: osixia/openldap:1.5.0
    restart: unless-stopped
    hostname: openldap
    container_name: openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - $PWD/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    environment:
      - LDAP_DOMAIN=activemq.apache.org
      - LDAP_BASE_DN=dc=activemq,dc=apache,dc=org
      - LDAP_ORGANISATION="Apache ActiveMQ Test Org"
      - LDAP_ROOTPASS=admin     
      - LDAP_ADMIN_PASSWORD=admin
    command: "--loglevel info --copy-service"   
    networks:
      ldap_net:
        ipv4_address: 172.28.1.10
    logging:
      driver: "none"
      options:
        max-size: "100M"
        max-file: "5"
  ldap-account-manager:
    image: ldapaccountmanager/lam:7.4
    restart: unless-stopped
    hostname: lam
    container_name: lam    
    links:
      - openldap    
    depends_on:
      - openldap  
    ports:
      - "8080:80"
      - "6443:6443"
    environment:
      - LAM_PASSWORD=${LAM_PASSWORD}
      - LAM_LANG=en_US
      - LDAP_SERVER=${LDAP_SERVER}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - ADMIN_USER=cn=admin,${LDAP_BASE_DN}
      - DEBUG=true
    networks:
      ldap_net:
        ipv4_address: 172.28.1.11      
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    hostname: phpldapadmin
    container_name: phpldapadmin
    links:
      - openldap    
    depends_on:
      - openldap
    ports:
      - "8180:80"
      - "6543:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    networks:
      ldap_net:
        ipv4_address: 172.28.1.12           
networks:
  ldap_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
