#!/usr/bin/env bash
# E2E test for the Samba AD domain-controller image (the alternative LDAP
# backend). Runs the DC container, waits for it to provision and start, then
# asserts it serves the Active Directory over LDAP.
#
# What it asserts: the container stays up, LDAP/LDAPS/Kerberos/Global-Catalog
# ports are listening, `samba-tool` shows a provisioned domain with the
# Administrator/krbtgt principals, and an authenticated LDAPS search returns
# the Administrator entry over the wire.
#
# Why --privileged: `samba-tool domain provision` sets NT ACLs (security.NTACL
# xattrs) on the sysvol tree; in an unprivileged container the kernel denies
# the xattr write ("{Access Denied} ... setntacl") and provisioning fails.
# This is a Samba-in-container requirement, independent of the base image.
#
# Assumes the image (SAMBA_IMAGE:SAMBA_VER) is already built — `make e2e-samba`
# builds it first. Provisioning scripts are bind-mounted from samba/ (the image
# intentionally does not bake them in).
set -euo pipefail

# Load committed defaults, then optional local overrides.
# shellcheck source=/dev/null
if [ -f .env.example ]; then set -a; . ./.env.example; set +a; fi
# shellcheck source=/dev/null
if [ -f .env         ]; then set -a; . ./.env;         set +a; fi

SAMBA_IMAGE="${SAMBA_IMAGE:-samba-ad}"
SAMBA_VER="${SAMBA_VER:-latest}"
# Image to run: prefer the fully-resolved ref the Makefile passes (it carries
# the DOCKER_LOGIN prefix when set, matching what `build-samba` tagged); else
# fall back to the bare name:tag from .env.example.
SAMBA_IMAGE_REF="${SAMBA_IMAGE_REF:-${SAMBA_IMAGE}:${SAMBA_VER}}"
SAMBA_CONTAINER="${SAMBA_CONTAINER:-samba-ad}"
SAMBA_HOST="${SAMBA_HOST:-dc.devad.example.com}"
SMB_ADMIN_PASSWORD="${SMB_ADMIN_PASSWORD:-P@ssw0rd123!}"
READY_TIMEOUT="${E2E_READY_TIMEOUT_SECONDS:-120}"
POLL="${E2E_POLL_INTERVAL_SECONDS:-2}"
SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../samba" && pwd)"

# Base DN derived from the realm (hostname): a.b.c -> DC=a,DC=b,DC=c
BASE_DN="DC=$(printf '%s' "$SAMBA_HOST" | sed 's/\./,DC=/g')"

PASS=0; FAIL=0
pass() { echo "  PASS: $1"; PASS=$((PASS + 1)); }
fail() { echo "  FAIL: $1"; FAIL=$((FAIL + 1)); }

cleanup() { docker rm -f "$SAMBA_CONTAINER" >/dev/null 2>&1 || true; }
trap cleanup EXIT

echo "=== E2E: Samba AD domain controller ==="
cleanup   # drop any stale container from a previous run

echo "== provisioning + starting the DC =="
# SMB_ADMIN_PASSWORD is passed env-only (no =VALUE in argv) so the demo password
# is not exposed via `ps -ef` / /proc/<pid>/cmdline. Docker forwards the value
# from this process's environment (sourced from .env.example above).
export SMB_ADMIN_PASSWORD
docker run -d --name "$SAMBA_CONTAINER" --privileged \
  --hostname "$SAMBA_HOST" \
  -e SMB_ADMIN_PASSWORD \
  -v "${SCRIPTS_DIR}:/opt/ad-scripts" \
  "${SAMBA_IMAGE_REF}" >/dev/null

echo "== wait for the DC to provision and serve LDAP =="
ready=
for _ in $(seq 1 $(( READY_TIMEOUT / POLL ))); do
  if ! docker ps --filter "name=^${SAMBA_CONTAINER}$" --filter status=running -q | grep -q .; then
    echo "  [container exited during provisioning]"
    break
  fi
  if docker exec "$SAMBA_CONTAINER" ss -tln 2>/dev/null | grep -qE ':389 '; then ready=1; break; fi
  sleep "$POLL"
done
if [ -n "$ready" ]; then
  pass "DC provisioned and LDAP is listening on :389"
else
  fail "DC did not start serving LDAP within ${READY_TIMEOUT}s"
  echo "--- last 25 log lines ---"; docker logs "$SAMBA_CONTAINER" 2>&1 | tail -25
  echo ""; echo "=== Results: ${PASS} passed, ${FAIL} failed ==="; exit 1
fi

echo "== AD service ports listening (ldap/ldaps/kerberos/global-catalog) =="
ports="$(docker exec "$SAMBA_CONTAINER" ss -tln 2>/dev/null || true)"
declare -A WHAT=( [389]="LDAP" [636]="LDAPS" [88]="Kerberos KDC" [3268]="Global Catalog" )
for p in 389 636 88 3268; do
  if printf '%s' "$ports" | grep -qE ":$p "; then pass "${WHAT[$p]} listening on :$p"
  else fail "${WHAT[$p]} NOT listening on :$p"; fi
done

echo "== AD directory provisioned (samba-tool reads sam.ldb) =="
domlevel="$(docker exec "$SAMBA_CONTAINER" samba-tool domain level show 2>&1 || true)"
if printf '%s' "$domlevel" | grep -qiE 'function level for domain'; then
  pass "domain provisioned ($(printf '%s' "$domlevel" | grep -i 'for domain' | head -1 | sed "s/.*for domain '//; s/'.*//"))"
else
  fail "domain level not readable — provisioning incomplete"
fi
users="$(docker exec "$SAMBA_CONTAINER" samba-tool user list 2>&1 || true)"
for u in Administrator krbtgt; do
  if printf '%s' "$users" | grep -qx "$u"; then pass "directory contains principal '$u'"
  else fail "directory missing principal '$u'"; fi
done

echo "== over-the-wire LDAP: authenticated LDAPS search =="
# Samba AD rejects simple binds over plaintext LDAP (requires encryption), so
# query over LDAPS using the DC's autogenerated self-signed cert (verification
# disabled for the test). Returning the Administrator DN proves an LDAP client
# can authenticate and read the directory across the container boundary.
ldap_out="$(docker exec -e LDAPTLS_REQCERT=never "$SAMBA_CONTAINER" \
  ldapsearch -LLL -x -H "ldaps://localhost:636" \
    -D "Administrator@${SAMBA_HOST}" -w "$SMB_ADMIN_PASSWORD" \
    -b "$BASE_DN" "(sAMAccountName=Administrator)" dn 2>&1 || true)"
if printf '%s' "$ldap_out" | grep -qiE "^dn: CN=Administrator,"; then
  pass "authenticated LDAPS search returned the Administrator entry"
else
  fail "LDAPS search did not return Administrator (got: $(printf '%s' "$ldap_out" | head -1))"
fi

echo ""
echo "=== Results: ${PASS} passed, ${FAIL} failed ==="
[ "$FAIL" -eq 0 ]
