version: "3.8"

services:
  openldap:
    image: osixia/openldap:1.5.0
    restart: unless-stopped
    hostname: openldap
    container_name: openldap
    ports:
      - "389:389"
      - "636:636"   
    volumes:
      - ../openldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    environment:
      - LDAP_DOMAIN=activemq.apache.org
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_ORGANISATION="Apache ActiveMQ Test Org"
      - LDAP_ROOTPASS=admin     
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_TLS_VERIFY_CLIENT="never"      
    command: "--loglevel info --copy-service"   
    networks:
      ldap_net:
        ipv4_address: 172.28.1.10
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"
  activemq:
    image: andriykalashnykov/docker-activemq:5.16.1
    restart: unless-stopped
    hostname: activemq
    container_name: activemq    
    links:
      - openldap    
    depends_on:
      - openldap  
    ports:
      - "1883:1883"
      - "5672:5672"
      - "8161:8161"
      - "61613:61613"
      - "61614:61614"
      - "61616:61616" 
    environment:
      - LDAP_HOST=openldap
      - LDAP_PORT=389
      - ACTIVEMQ_OPTS_MEMORY=-Xms512M -Xmx2G
      - PERCENT_JVM_HEAP=75
      - STORE_USAGE=${ACTIVEMQ_STORE_USAGE}
      - TEMP_USAGE=${ACTIVEMQ_TEMP_USAGE}
      - DEBUG=true
    networks:
      ldap_net:
        ipv4_address: 172.28.1.11
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    hostname: phpldapadmin
    container_name: phpldapadmin
    links:
      - openldap    
    depends_on:
      - openldap
    ports:
      - "6543:443"    
      # - "8180:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      # - PHPLDAPADMIN_HTTPS=false
    networks:
      ldap_net:
        ipv4_address: 172.28.1.12  
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"          
    command: "--loglevel info --copy-service"                       
networks:
  ldap_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
