version: "3.8"

services:
  openldap:
    image: osixia/openldap:1.5.0
    restart: unless-stopped
    hostname: ${LDAP_SERVER_HOST}
    container_name: ${LDAP_SERVER_HOST}
    ports:
      - "389:389"
      - "636:636"   
    volumes:
      - ../openldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    environment:
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_ROOTPASS=${LDAP_USER_PWD}     
      - LDAP_ADMIN_PASSWORD=${LDAP_USER_PWD}
      - LDAP_TLS_VERIFY_CLIENT="never"     
      - LDAP_TLS_CIPHER_SUITE=SECURE256:+SECURE128:+VERS-TLS-ALL:+VERS-TLS1.2:+RSA:+DHE-DSS:+CAMELLIA-128-CBC:+CAMELLIA-256-CBC 
    command: "--loglevel info --copy-service"   
    networks:
      ldap_net:
        ipv4_address: 172.28.1.10
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILES}"
  activemq:
    image: andriykalashnykov/docker-activemq:5.16.1
    restart: unless-stopped
    hostname: activemq
    container_name: activemq    
    links:
      - ${LDAP_SERVER_HOST}    
    depends_on:
      - ${LDAP_SERVER_HOST}  
    ports:
      - "1883:1883"
      - "5672:5672"
      - "8161:8161"
      - "61613:61613"
      - "61614:61614"
      - "61616:61616" 
    environment:
      - LDAP_HOST=${LDAP_SERVER_HOST}
      - LDAP_PORT=${LDAP_SERVER_PORT}
      - LDAP_CONN_USER=${LDAP_USER}
      - LDAP_CONN_USER_PWD=${LDAP_USER_PWD}
      - LDAP_QUEUE_SEARCH_BASE=${LDAP_QUEUE_SEARCH_BASE}
      - LDAP_TOPIC_SEARCH_BASE=${LDAP_TOPIC_SEARCH_BASE}
      - LDAP_TEMP_SEARCH_BASE=${LDAP_TEMP_SEARCH_BASE}
      - LDAP_REFRESH_INTERVAL=${LDAP_REFRESH_INTERVAL}
      - LDAP_LEGACY_GROUP_MAPPING=${LDAP_LEGACY_GROUP_MAPPING}
      - LDAP_USER_BASE=${LDAP_USER_BASE}
      - LDAP_ROLE_BASE=${LDAP_ROLE_BASE}
      - OPTS_MEMORY=${ACTIVEMQ_OPTS_MEMORY}
      - PERCENT_JVM_HEAP=${ACTIVEMQ_PERCENT_JVM_HEAP}
      - STORE_USAGE=${ACTIVEMQ_STORE_USAGE}
      - TEMP_USAGE=${ACTIVEMQ_TEMP_USAGE}
      - DEBUG=true
    networks:
      ldap_net:
        ipv4_address: 172.28.1.11
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILES}"
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    hostname: phpldapadmin
    container_name: phpldapadmin
    links:
      - openldap    
    depends_on:
      - openldap
    ports:
      - "6443:443"    
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    networks:
      ldap_net:
        ipv4_address: 172.28.1.12  
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILES}"          
    command: "--loglevel info --copy-service"                       
networks:
  ldap_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
