#!/bin/bash

# set -x

# DOCKER_LOGIN=
# DOCKER_PWD=
DOCKER_REGISTRY=registry-1.docker.io

ACTIVEMQ_VER=5.19.6
JETTY_VER=9.4.58.v20250814
LDAPTIVE_VER=2.5.0
ACTIVEMQ_IMAGE_NAME=docker-activemq

APACHEDS_IMAGE_NAME=apacheds-ad
APACHEDS_VER=latest

OPENLDAP_CONTAINER=openldap
PHPLDAPADMIN_CONTAINER=phpldapadmin
ACTIVEMQ_CONTAINER=activemq

