#!/bin/bash

# set -x

# DOCKER_LOGIN=
# DOCKER_PWD=
DOCKER_REGISTRY=registry-1.docker.io

ACTIVEMQ_VER=5.16.1
JETTY_VER=9.4.35.v20201120
LDAPTIVE_VER=1.2.4
ACTIVEMQ_IMAGE_NAME=docker-activemq

APACHEDS_IMAGE_NAME=apacheds-ad
APACHEDS_VER=latest

OPENLDAP_CONTAINER=openldap
PHPLDAPADMIN_CONTAINER=phpldapadmin
ACTIVEMQ_CONTAINER=activemq

