#!/bin/bash

# set -x

# DOCKER_LOGIN=
# DOCKER_PWD=
DOCKER_REGISTRY=registry-1.docker.io

ACTIVEMQ_VER=6.2.6
JETTY_VER=11.0.26
ACTIVEMQ_IMAGE_NAME=docker-activemq

APACHEDS_IMAGE_NAME=apacheds-ad
APACHEDS_VER=latest

OPENLDAP_CONTAINER=openldap
PHPLDAPADMIN_CONTAINER=phpldapadmin
ACTIVEMQ_CONTAINER=activemq

