version: "3.8"

services:
  apacheds-ad:
    image: andriykalashnykov/apacheds-ad:latest
    restart: unless-stopped
    hostname: apacheds-ad
    container_name: apacheds-ad
    ports:
      - "10389:10389"
    # volumes:
    #   - ../openldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    #   - /var/lib/ldap
    #   - /etc/ldap/slapd.d
    #   - /container/service/slapd/assets/certs/
    # environment:
    #   - LDAP_DOMAIN=activemq.apache.org
    #   - LDAP_BASE_DN=${LDAP_BASE_DN}
    #   - LDAP_ORGANISATION="Apache ActiveMQ Test Org"
    #   - LDAP_ROOTPASS=admin     
    #   - LDAP_ADMIN_PASSWORD=admin
    #   - LDAP_TLS_VERIFY_CLIENT="never"      
    command: ""   
    networks:
      ldap_net:
        ipv4_address: 172.38.2.10
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    hostname: phpldapadmin
    container_name: phpldapadmin
    links:
      - apacheds-ad    
    depends_on:
      - apacheds-ad
    ports:
      - "6543:443"    
      # - "8180:80"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[
        {'lapacheds-ad':[
          {'server': [
            {'tls': False},
            {'port': 10389},
            {'base': \"array('dc=wimpi,dc=net')\"}
          ]
          },
          {'login': [
            {'bind_id': 'uid=test,ou=users,dc=wimpi,dc=net'},
            {'bind_pass': '${LDAP_ADMIN_PASSWORD:-secret}'}
          ]
          }
        ]
        }
        ]"
    networks:
      ldap_net:
        ipv4_address: 172.38.2.11  
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"          
    command: "--loglevel debug --copy-service"                       
networks:
  ldap_net:
    ipam:
      driver: default
      config:
        - subnet: 172.38.0.0/16
