version: "3.8"

services:
  apacheds:
    image: andriykalashnykov/apacheds-ad:latest
    restart: unless-stopped
    hostname: ${LDAP_SERVER_HOST}
    container_name: ${LDAP_SERVER_HOST}
    ports:
      - "10389:${LDAP_SERVER_PORT}"
    volumes:
      - ./ldif:/ldap/ldif
    command: ""   
    networks:
      ldap_net:
        ipv4_address: ${IPV4_ADDRESS_PREFIX}.2.10
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILES}"
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    hostname: ${PHPLDAPADMIN_SERVER_HOST}
    container_name: ${PHPLDAPADMIN_SERVER_HOST}
    links:
      - ${LDAP_SERVER_HOST}    
    depends_on:
      - ${LDAP_SERVER_HOST}
    ports:
      - "6543:${PHPLDAPADMIN_SERVER_PORT}"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[
        {'${LDAP_SERVER_HOST}':[
          {'server': [
            {'tls': ${LDAP_SERVER_TLS}},
            {'port': ${LDAP_SERVER_PORT}},
            {'base': \"array('${LDAP_BASE_DN}')\"}
          ]
          },
          {'login': [
            {'bind_id': '${LDAP_USER}'},
            {'bind_id': '${LDAP_USER}'},
            {'auth_type': 'session'}
          ]
          }
        ]
        }
        ]"
    networks:
      ldap_net:
        ipv4_address: ${IPV4_ADDRESS_PREFIX}.2.11  
    logging:
      driver: "${LOG_DRIVER}"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILES}"          
    command: "--loglevel debug --copy-service"                       
networks:
  ldap_net:
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_ADDRESS_PREFIX}.0.0/16
